

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tapr-images
  namespace: user-system-{{ .Values.bfl.username }}
  labels:
    applications.app.bytetrade.io/author: bytetrade.io
  annotations:
    applications.app.bytetrade.io/version: '0.0.1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tapr-images
  template:
    metadata:
      labels:
        app: tapr-images
    spec:
      serviceAccountName: tapr-images
      serviceAccount: tapr-images
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: init-data
          image: busybox:1.28
          securityContext:
            privileged: true
            runAsNonRoot: false
            runAsUser: 0
          volumeMounts:
          - name: image-upload
            mountPath: /data
          command:
          - sh
          - -c
          - |
            chown -R 1000:1000 /data 
      containers:
      - name: tapr-images-uploader
        image: beclab/images-uploader:0.1.2
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: image-upload
          mountPath: /data
        env:
        - name: BFL
          value: bfl.user-space-{{ .Values.bfl.username }}
      volumes:
      - name: image-upload
        hostPath:
          type: DirectoryOrCreate
          path: {{ .Values.userspace.userData }}/Pictures

---
apiVersion: v1
kind: Service
metadata:
  name: tapr-images-svc
  namespace: user-system-{{ .Values.bfl.username }}
spec:
  selector:
    app: tapr-images
  type: ClusterIP
  ports:
    - protocol: TCP
      name: tapr-image
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tapr-images
  namespace: user-system-{{ .Values.bfl.username }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-system-{{ .Values.bfl.username }}:tapr-images
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tapr-images-role
subjects:
- kind: ServiceAccount
  name: tapr-images
  namespace: user-system-{{ .Values.bfl.username }}