apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: backupconfigs.sys.bytetrade.io
spec:
  group: sys.bytetrade.io
  names:
    categories:
    - all
    kind: BackupConfig
    listKind: BackupConfigList
    plural: backupconfigs
    shortNames:
    - bc
    singular: backupconfig
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.provider
      name: provider
      type: string
    - jsonPath: .spec.region
      name: region
      type: string
    - jsonPath: .spec.bucket
      name: bucket
      type: string
    - jsonPath: .spec.prefix
      name: prefix
      type: string
    - jsonPath: .spec.owner
      name: owner
      type: string
    - jsonPath: .spec.location
      name: location
      type: string
    - jsonPath: .spec.storageLocation
      name: storageLocation
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: age
      type: date
    - jsonPath: .status.updateTime
      name: updateTime
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: BackupConfig is the Schema for the backupconfigs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: BackupConfigSpec defines the desired state of BackupConfig
            properties:
              accessKey:
                type: string
              backupPolicy:
                properties:
                  enabled:
                    type: boolean
                  name:
                    type: string
                  snapshotFrequency:
                    type: string
                  timesOfDay:
                    type: string
                  dayOfWeek:
                    format: int64
                    type: integer
                required:
                - enabled
                - name
                - snapshotFrequency
                - timesOfDay
                type: object
              bucket:
                type: string
              extra:
                additionalProperties:
                  type: string
                type: object
              location:
                type: string
              owner:
                type: string
              plugins:
                items:
                  type: string
                type: array
              prefix:
                type: string
              provider:
                type: string
              region:
                type: string
              repositoryPassword:
                type: string
              s3Url:
                type: string
              secretKey:
                type: string
              storageLocation:
                type: string
            required:
            - bucket
            - location
            - plugins
            - provider
            - region
            - storageLocation
            type: object
          status:
            description: BackupConfigStatus defines the observed state of BackupConfig
            properties:
              state:
                description: 'INSERT ADDITIONAL STATUS FIELD - define observed state of cluster Important: Run "make" to regenerate code after modifying this file'
                type: string
              updateTime:
                format: date-time
                type: string
            required:
            - state
            - updateTime
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
