

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-server-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    applications.app.bytetrade.io/author: bytetrade.io
  annotations:
    applications.app.bytetrade.io/version: '0.0.1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-server
  template:
    metadata:
      labels:
        app: monitoring-server
    spec:
      containers:
      - name: monitoring-server
        image: beclab/monitoring-server-v1:v0.2.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: monitoring-server
  type: ClusterIP
  ports:
    - protocol: TCP
      name: monitoring-server
      port: 80
      targetPort: 8000