


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rss-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: rss-server
    applications.app.bytetrade.io/author: bytetrade.io
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rss-server
  template:
    metadata:
      labels:
        app: rss-server
    spec:
      containers:
        - name: rss-server
          image: beclab/rsshub:v0.0.2
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3010

---
apiVersion: v1
kind: Service
metadata:
  name: rss-server
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: rss-server
  ports:
    - name: server
      protocol: TCP
      port: 3010
      targetPort: 3010
 