
bfl:
  username: 'test'
  url: 'test'
  nodeName: test
pvc:
  userspace: test
userspace:
  userData: test/Home
  appData: test/Data
  appCache: test
  dbdata: test
os:
  portfolio:
    appKey: '${ks[0]}'
    appSecret: test
  vault:
    appKey: '${ks[0]}'
    appSecret: test
  desktop:
    appKey: '${ks[0]}'
    appSecret: test
  message:
    appKey: '${ks[0]}'
    appSecret: test
  rss:
    appKey: '${ks[0]}'
    appSecret: test
  search:
    appKey: '${ks[0]}'
    appSecret: test
  search2:
    appKey: '${ks[0]}'
    appSecret: test
  appstore:
    appKey: '${ks[0]}'
    appSecret: test
kubesphere:
  redis_password: ""
