

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: osnodeinit-daemon
  namespace: {{ .Release.Namespace }}
  labels:
    app: osnodeinit-daemon
    applications.app.bytetrade.io/author: bytetrade.io
spec:
  selector:
    matchLabels:
      app: osnodeinit-daemon
  template:
    metadata:
      labels:
        app: osnodeinit-daemon
    spec:
      serviceAccountName: os-internal
      serviceAccount: os-internal
      hostNetwork: true
      containers:
      - name: daemon
        image: beclab/osnode-init:v0.0.10
        imagePullPolicy: IfNotPresent
        args:
        - --metrics-bind-address
        - :18888
        - --health-probe-bind-address
        - :18881
        env:
        {{- range $key, $val := .Values.terminusGlobalEnvs }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: "status.hostIP"
        - name: S3_BUCKET
          value: {{ .Values.s3_bucket }}
        - name: APP_RANDOM_KEY
          valueFrom:
            secretKeyRef:
              name: app-key
              key: random-key
        resources:
          requests:
            cpu: 20m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        volumeMounts:
          - name: terminus
            mountPath: /olares
          - name: bin
            mountPath: /usr/local/bin/juicefs
            subPath: juicefs
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: terminus
        hostPath:
          path: {{ .Values.rootPath }}
      - name: bin
        hostPath:
          path: /usr/local/bin
