
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bytetrade-sys-ops
  namespace: user-system-{{ .Values.bfl.username }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-system-{{ .Values.bfl.username }}:bytetrade-sys-ops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sys-editor-role
subjects:
- kind: ServiceAccount
  name: bytetrade-sys-ops
  namespace: user-system-{{ .Values.bfl.username }}


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-server
  namespace: user-system-{{ .Values.bfl.username }}
  labels:
    app: systemserver
    applications.app.bytetrade.io/author: bytetrade.io
  annotations:
    applications.app.bytetrade.io/version: '0.0.1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: systemserver
  template:
    metadata:
      labels:
        app: systemserver
    spec:
      serviceAccountName: bytetrade-sys-ops
      serviceAccount: bytetrade-sys-ops
      containers:
      - name: system-server
        image: beclab/system-server:0.1.18
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        command:
        - /system-server
        - -v
        - "4"
        env:
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OWNER
          value: {{ .Values.bfl.username }}
      - name: proxy
        image: bytetrade/envoy:v1.25.11
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
        ports:
        - name: redis-proxy
          containerPort: 6379
        - name: mongo-proxy
          containerPort: 27017
        - name: pg-proxy
          containerPort: 5432
        - name: auth-proxy
          containerPort: 9091
        - name: knowledge-proxy
          containerPort: 3010
        - name: fakes3-proxy
          containerPort: 4568
        volumeMounts:
        - name: proxy-config
          readOnly: true
          mountPath: /etc/envoy/envoy.yaml
          subPath: envoy.yaml
        command:
        - /usr/local/bin/envoy
        - --log-level
        - debug
        - -c
        - /etc/envoy/envoy.yaml
        env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      volumes:
      - name: proxy-config
        configMap:
          name: systemserver-proxy-configs
          items:
          - key: envoy.yaml
            path: envoy.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: system-server
  namespace: user-system-{{ .Values.bfl.username }}
spec:
  type: ClusterIP
  selector:
    app: systemserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
data:
  envoy.yaml: |
    static_resources:
      listeners:
        - name: listener_redis_proxy
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 6379
          filter_chains:
            - filters:
                - name: envoy.filters.network.tcp_proxy
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                    stat_prefix: destination
                    cluster: cluster_redis_proxy
        - name: listener_mongo_proxy
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 27017
          filter_chains:
            - filters:
                - name: envoy.filters.network.tcp_proxy
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                    stat_prefix: destination
                    cluster: cluster_mongo_proxy
        - name: listener_pg_proxy
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 5432
          filter_chains:
            - filters:
                - name: envoy.filters.network.tcp_proxy
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                    stat_prefix: destination
                    cluster: cluster_pg_proxy
        - name: listener_auth_backend_proxy
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 9091
          filter_chains:
            - filters:
                - name: envoy.filters.network.tcp_proxy
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                    stat_prefix: destination
                    cluster: cluster_auth_backend_proxy
        - name: listener_knowledge_api_proxy
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 3010
          filter_chains:
            - filters:
                - name: envoy.filters.network.tcp_proxy
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                    stat_prefix: destination
                    cluster: cluster_knowledge_api_proxy
        - name: listener_fakes3_proxy
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 4568
          filter_chains:
            - filters:
                - name: envoy.filters.network.tcp_proxy
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                    stat_prefix: destination
                    cluster: cluster_fakes3_proxy
      clusters:
        - name: cluster_redis_proxy
          connect_timeout: 30s
          type: LOGICAL_DNS
          dns_lookup_family: V4_ONLY
          load_assignment:
            cluster_name: cluster_redis_proxy
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: redis-cluster-proxy.os-system.svc.cluster.local
                          port_value: 6379  
        - name: cluster_mongo_proxy
          connect_timeout: 30s
          type: LOGICAL_DNS
          dns_lookup_family: V4_ONLY
          load_assignment:
            cluster_name: cluster_mongo_proxy
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: mongo-cluster-mongos.os-system.svc.cluster.local
                          port_value: 27017  
        - name: cluster_pg_proxy
          connect_timeout: 30s
          type: LOGICAL_DNS
          dns_lookup_family: V4_ONLY
          load_assignment:
            cluster_name: cluster_pg_proxy
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: citus-0.citus-headless.os-system.svc.cluster.local
                          port_value: 5432
        - name: cluster_auth_backend_proxy
          connect_timeout: 30s
          type: LOGICAL_DNS
          dns_lookup_family: V4_ONLY
          load_assignment:
            cluster_name: cluster_auth_backend_proxy
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: authelia-backend.os-system.svc.cluster.local
                          port_value: 9091  
        - name: cluster_knowledge_api_proxy
          connect_timeout: 30s
          type: LOGICAL_DNS
          dns_lookup_family: V4_ONLY
          load_assignment:
            cluster_name: cluster_knowledge_api_proxy
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: rss-svc.user-space-{{ .Values.bfl.username }}.svc.cluster.local
                          port_value: 3010  
        - name: cluster_fakes3_proxy
          connect_timeout: 30s
          type: LOGICAL_DNS
          dns_lookup_family: V4_ONLY
          load_assignment:
            cluster_name: cluster_fakes3_proxy
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: tapr-s3-svc.os-system.svc.cluster.local
                          port_value: 4568  
kind: ConfigMap
metadata:
  name: systemserver-proxy-configs
  namespace: user-system-{{ .Values.bfl.username }}

    