

{{- $namespace := printf "%s%s" "user-system-" .Values.bfl.username -}}
{{- $agent_secret := (lookup "v1" "Secret" $namespace "agent-secrets") -}}
{{- $password := "" -}}
{{ if $agent_secret -}}
{{ $password = (index $agent_secret "data" "pg_password") }}
{{ else -}}
{{ $password = randAlphaNum 16 | b64enc }}
{{- end -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: agent-secrets
  namespace: user-system-{{ .Values.bfl.username }}
type: Opaque
data:
  pg_password: {{ $password }}
---
apiVersion: apr.bytetrade.io/v1alpha1
kind: MiddlewareRequest
metadata:
  name: agent-pg
  namespace: user-system-{{ .Values.bfl.username }}
spec:
  app: agent
  appNamespace: {{ .Release.Namespace }}
  middleware: postgres
  postgreSQL:
    user: agent_{{ .Values.bfl.username }}
    password:
      valueFrom:
        secretKeyRef:
          key: pg_password
          name: agent-secrets
    databases:
    - name: agent   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: agent
    applications.app.bytetrade.io/author: bytetrade.io
    applications.app.bytetrade.io/name: agent
    applications.app.bytetrade.io/owner: {{ .Values.bfl.username }}
  annotations:
    applications.app.bytetrade.io/icon: https://file.bttcdn.com/appstore/agent/icon.png
    applications.app.bytetrade.io/title: agent
    applications.app.bytetrade.io/version: '0.0.1'
    applications.app.bytetrade.io/entrances: '[{"name":"agent", "host":"agent-service", "port":80,"title":"agent","invisible": true}]'
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      initContainers:
      - name: terminus-sidecar-init
        image: openservicemesh/init:v1.2.3
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          capabilities: 
            add:
            - NET_ADMIN
          runAsNonRoot: false
          runAsUser: 0
        command:
        - /bin/sh
        - -c
        - |
          iptables-restore --noflush <<EOF
          # sidecar interception rules
          *nat
          :PROXY_IN_REDIRECT - [0:0]
          :PROXY_INBOUND - [0:0]
          -A PROXY_IN_REDIRECT -p tcp -j REDIRECT --to-port 15003
          -A PROXY_INBOUND -p tcp --dport 15000 -j RETURN
          -A PROXY_INBOUND -p tcp -j PROXY_IN_REDIRECT
          -A PREROUTING -p tcp -j PROXY_INBOUND
          COMMIT
          EOF
        
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
      containers:
      - name: frontend
        image: nginx:stable-alpine3.17-slim
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        ports:
        - containerPort: 80
      - name: terminus-envoy-sidecar
        image: envoyproxy/envoy-distroless:v1.25.2
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
        ports:
        - name: proxy-admin
          containerPort: 15000
        - name: proxy-inbound
          containerPort: 15003
        volumeMounts:
        - name: terminus-sidecar-config
          readOnly: true
          mountPath: /etc/envoy/envoy.yaml
          subPath: envoy.yaml
        command:
        - /usr/local/bin/envoy
        - --log-level
        - debug
        - -c
        - /etc/envoy/envoy.yaml
        env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      - name: dify-gateway
        image: beclab/search2-gateway:v0.0.34
        imagePullPolicy: IfNotPresent
        ports:
          - name: dify-gateway
            containerPort: 6317
            protocol: TCP
        env:
          - name: OS_SYSTEM_SERVER
            value: system-server.user-system-{{ .Values.bfl.username }}
          - name: OS_APP_SECRET
            value: '{{ .Values.os.agent.appSecret }}'
          - name: OS_APP_KEY
            value: {{ .Values.os.agent.appKey }}
          - name: PREFIX
            value: /api/controllers
          - name: DIFY_ADMIN_USER_EMAIL
            value: admin@bytetrade.io
          - name: DIFY_ADMIN_USER_PASSWORD
            value: abcd123456
          - name: DIFY_USER_NAME
            value: {{ .Values.bfl.username }}
          - name: DIFY_USER_PASSWORD
            value: abcd123456
          - name: WATCH_DIR
            value: /Home/Documents
          - name: PG_USERNAME
            value: agent_{{ .Values.bfl.username }}
          - name: PG_PASSWORD
            value: {{ $password | b64dec }}
          - name: PG_HOST
            value: citus-master-svc.user-system-{{ .Values.bfl.username }}
          - name: PG_PORT
            value: "5432"
          - name: PG_DATABASE
            value: user_space_{{ .Values.bfl.username }}_agent
          - name: DIFY_HOST
            value: http://dify
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CONTAINER_NAME
            value: dify-gateway
          - name: NOTIFY_SERVER
            value: fsnotify-svc.user-system-{{ .Values.bfl.username }}:5079
          {{- if and .Values.gpu (not (eq .Values.gpu "none" )) }}
          - name: GPU
            value: {{ .Values.gpu }}
          {{- end }}
        volumeMounts:
          - name: watch-dir
            mountPath: /Home/Documents
          - name: userspace-dir
            mountPath: /Home

      volumes:
      - name: terminus-sidecar-config
        configMap:
          name: sidecar-configs
          items:
          - key: envoy.yaml
            path: envoy.yaml
      - name: watch-dir
        hostPath:
          type: Directory
          path: {{ .Values.userspace.userData }}/Documents

      - name: userspace-dir
        hostPath:
          type: Directory
          path: {{ .Values.userspace.userData }}

      - name: nginx-config
        configMap:
          name: agent-nginx-configs
          items:
          - key: nginx.conf
            path: nginx.conf

---
apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: agent
  ports:
  - name: "dify-gateway"
    protocol: TCP
    port: 6317
    targetPort: 6317
  - name: "agent-frontend"
    protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: sys.bytetrade.io/v1alpha1
kind: ProviderRegistry
metadata:
  name: dify-gateway-provider
  namespace: user-system-{{ .Values.bfl.username }}
spec:
  dataType: gateway
  deployment: agent-deployment
  description: dify gateway provider
  endpoint: agent-service.{{ .Release.Namespace }}
  group: service.agent
  kind: provider
  namespace: {{ .Release.Namespace }}
  opApis:
    - name: DifyGatewayBaseProvider
      uri: /api/controllers/dify_gateway_base_provider
  version: v1
status:
  state: active

---
apiVersion: sys.bytetrade.io/v1alpha1
kind: ApplicationPermission
metadata:
  name: dify-gateway
  namespace: user-system-{{ .Values.bfl.username }}
spec:
  app: agent
  appid: agent
  key: {{ .Values.os.agent.appKey }}
  secret: {{ .Values.os.agent.appSecret }}
  permissions:
    - dataType: files
      group: service.files
      ops:
        - GetDatasetFolderStatus
      version: v1
status:
  state: active

---
apiVersion: v1
data:
  nginx.conf: |
    # Configuration checksum:
    pid /var/run/nginx.pid;
    worker_processes 2;
    worker_rlimit_nofile 65535;
    worker_shutdown_timeout 240s ;
    events {
      multi_accept        on;
      worker_connections  16384;
      use                 epoll;
    }
    http {
      aio                 threads;
      aio_write           on;
      tcp_nopush          on;
      tcp_nodelay         on;
      log_subrequest      on;
      reset_timedout_connection on;
      keepalive_timeout  75s;
      keepalive_requests 100;
      client_body_temp_path           /tmp/client-body;
      fastcgi_temp_path               /tmp/fastcgi-temp;
      proxy_temp_path                 /tmp/proxy-temp;
      client_max_body_size            1g;
      client_header_buffer_size       1k;
      client_header_timeout           60s;
      large_client_header_buffers     4 8k;
      client_body_buffer_size         8k;
      client_body_timeout             60s;
      types_hash_max_size             2048;
      server_names_hash_max_size      4096;
      server_names_hash_bucket_size   1024;
      map_hash_bucket_size            64;
      proxy_headers_hash_max_size     512;
      proxy_headers_hash_bucket_size  64;
      variables_hash_bucket_size      256;
      variables_hash_max_size         2048;
      underscores_in_headers          off;
      ignore_invalid_headers          on;
      include /etc/nginx/mime.types;
      default_type text/html;
      gzip on;
      gzip_comp_level 1;
      gzip_http_version 1.1;
      gzip_min_length 256;
      gzip_types application/atom+xml application/javascript application/x-javascript application/json application/rss+xml application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/svg+xml image/x-icon text/css text/javascript text/plain text/x-component;
      gzip_proxied any;
      gzip_vary on;
      # Custom headers for response
      server_tokens off;
      server_name_in_redirect off;
      port_in_redirect        off;
      # global log
      log_format main $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time "$http_x_forwarded_for";
      access_log /var/log/nginx/access.log main;
      error_log /var/log/nginx/error.log error;
      proxy_ssl_session_reuse on;
      # Global filters
      # timeout
      resolver_timeout        30s;
      send_timeout            60s;
      map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
      }

      server {
        listen 80 default_server;

        # Gzip Settings
        gzip off;
        gzip_disable "msie6";
        gzip_min_length 1k;
        gzip_buffers 16 64k;
        gzip_http_version 1.1;
        gzip_comp_level 6;
        gzip_types *;
        root /app;

        # normal routes
        # serve given url and default to index.html if not found
        # e.g. /, /user and /foo/bar will return index.html
        location / {
          try_files $uri $uri/index.html /index.html;
          add_header Cache-Control "private,no-cache";
          add_header Last-Modified "Oct, 03 Jan 2022 13:46:41 GMT";
              expires 0;
        }


        location /api/controllers {
            add_header Access-Control-Allow-Headers "access-control-allow-headers,access-control-allow-methods,access-control-allow-origin,content-type,x-auth,x-unauth-error,x-authorization";
            add_header Access-Control-Allow-Methods "PUT, GET, DELETE, POST, OPTIONS";
            add_header Access-Control-Allow-Origin $http_origin;
            add_header Access-Control-Allow-Credentials true;

            proxy_pass http://127.0.0.1:6317;
            proxy_set_header            Host $host;
            proxy_set_header            X-real-ip $remote_addr;
            proxy_set_header            X-Forwarded-For $proxy_add_x_forwarded_for;

            add_header X-Frame-Options SAMEORIGIN;
            # rewrite ^/server(.*)$ $1 break;

            if ($request_method = 'OPTIONS') {
                return 204;
            }
        }



        # # files
        # # for all routes matching a dot, check for files and return 404 if not found
        # # e.g. /file.js returns a 404 if not found
        location ~.*\.(js|css|png|jpg|svg|woff|woff2)$
          {
              add_header Cache-Control "public, max-age=2678400";
          }
      }
    }
kind: ConfigMap
metadata:
  name: agent-nginx-configs
  namespace: {{ .Release.Namespace }}
